package tw.andrew;
/*
 * This class create new data of pressure which generated by the set point +/- the accuracy.
 */


import java.math.BigDecimal;

class Pressure {
	double presSetPoint; // Unit: kPa
	double presAccuracy;
	double presRange;
	double tempPres;
	
	Pressure(double pressureSetPoint, double pressureAccuracy) {
		this.presSetPoint = pressureSetPoint;
		this.presAccuracy = pressureAccuracy;
		presRange = presSetPoint * (Math.random() * presAccuracy);
	}
	
	String getPressure() {
		if ( (int)(Math.random()*2) == 1) { // Set Point + Range
			tempPres = presSetPoint + presRange;		
		}else { // Set Point - Range
			tempPres = presSetPoint - presRange;		
		}
		BigDecimal pres = new BigDecimal(tempPres).setScale(1, BigDecimal.ROUND_HALF_UP); // 取小數點後第一位，四捨五入
		String pressure = pres.toString();
		
		return pressure;
	}
}
