package tw.andrew;
/*
 * This class create new data of temperature which generated by the set point +/- the accuracy.
 */


import java.math.BigDecimal;

class Temperature {
	double tempSetPoint; // Unit: degree C
	double tempAccuracy;
	double tempRange;
	double tempTemp;
	
	Temperature(double temperatureSetPoint, double temperatureAccuracy) {
		this.tempSetPoint = temperatureSetPoint;
		this.tempAccuracy = temperatureAccuracy;
		tempRange = tempSetPoint * (Math.random() * tempAccuracy);
	}
	
	String getTemperature() {
		if ( (int)(Math.random()*2) == 1) { // Set Point + Range
			tempTemp = tempSetPoint + tempRange;		
		}else { // Set Point - Range
			tempTemp = tempSetPoint - tempRange;		
		}
		BigDecimal temp = new BigDecimal(tempTemp).setScale(1, BigDecimal.ROUND_HALF_UP); // 取小數點後第一位，四捨五入
		String temperature = temp.toString();
		
		return temperature;
	}
}
